config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :categories

  root 'home#index'
  post '/' => 'cards#set_active'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :category
  before_save :set_all_inactive
  before_save :set_active_if_new_category
    
  scope :active, -> { where(active: true) }
  
  def display_title
    self.title.titleize
  end
  
  def set_all_inactive
    Card.where(:category => self.category).update_all(active: false) if self.active == true
  end
  
  def set_active_if_new_category
    @card = Card.where(:category => self.category).active
    logger.debug "Checking..."
    if @card.empty?
      logger.debug "No ative card, setting this to ture."
      self.active = true
    end
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  def display_name 
    self.name.titleize
  end
  def file_name 
    self.name.downcase.tr(" ", "_")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.includes(:category).order('categories.name, cards.title').all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end
 
  # POST /
  def set_active
    @card = Card.find(params[:card][:id])    
    @card.update_attributes(:active => 'true')
    
    redirect_to root_path, notice: 'Card was successfully updated.' if @card   
  end
  
  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:category_id, :title, :p_1, :p_2, :p_3, :p_4, :p_5, :active)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cards = []
    @all_categories = Category.all
    @all_cards = Card.all
    
    @all_categories.each do |category|
      card = Card.includes(:category).where('categories.name' => category.name).active.first
      @cards.push(card) if card
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  
  def p_row(text)
    "<p class=\"list-group-item-text\">#{text}</p>".html_safe unless text == ''
  end
  
  def render_card(card)
    unless card.blank?
      render partial: '/cards/card', locals: {card: card}
    end
  end
  
  def display_active_star(card)
    "<i class=\"fa fa-lg fa-star\"></i>".html_safe if(card.active)
  end
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/_card.html.erb
<!-- views/cards/_card.html.erb -->
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h3 class="panel-title pull-left"><%= card.category.display_name %></h3>
          <span class="pull-right">
            <a data-toggle="modal" data-target="#<%= card.category.file_name %>" rel="modal:open">
              Change
            </a>
          </span>     
        </div>
        <div class="panel-body text-center">
            <p class="list-group-item-text"><h3><%= card.title %></h3></p>
            <%= p_row(card.p_1) %>
            <%= p_row(card.p_2) %>
            <%= p_row(card.p_3) %>
            <%= p_row(card.p_4) %>
            <%= p_row(card.p_5) %>
        </div>
        <div class="panel-footer">
          <small>Last updated on <%= card.updated_at.strftime("%A, %B %d, %Y at %H:%M %Z") %> by #915</small>
        </div>
    </div>
</div>
<div class="modal fade" id="<%= card.category.file_name %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"> Change <%= card.category.display_name %></h4>
      </div>
      <%= form_tag ('/') do |f| %>
      <div class="modal-body">
          <div class="form-group">
            <%= collection_select(:card, :id, Card.includes(:category).where('categories.name' => card.category.name).all, :id, :title, { :prompt=>true }, { :class=>'form-control' }) %>
            <%= hidden_field_tag 'card[category_id]', card.category.id %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag 'Update', :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
<% if @card.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

  <ul>
    <% @card.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="col-sm-5">
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left"><%= yield :card_title %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :title %> </div>
        <div class="col-sm-10 form-group"><%= f.text_field :title, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :category %> </div>
        <div class="col-sm-10 form-group"><%= f.collection_select :category_id, Category.order(:name).all, :id, :display_name, {}, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :category %> </div>
        <div class="col-sm-10 form-group"><%= f.select :active, [['Active', true], ['Inactive', false]], {}, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :p_1, "Line 1" %> </div>
        <div class="col-sm-10 form-group"><%= f.text_field :p_1, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :p_2, "Line 2" %> </div>
        <div class="col-sm-10 form-group"><%= f.text_field :p_2, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :p_3, "Line 3" %> </div>
        <div class="col-sm-10 form-group"><%= f.text_field :p_3, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :p_4, "Line 4" %> </div>
        <div class="col-sm-10 form-group"><%= f.text_field :p_4, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-2 form-group"><%= f.label :p_5, "Line 5"%> </div>
        <div class="col-sm-10 form-group"><%= f.text_field :p_5, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="btn-group pull-right">
            <a onclick="history.go(-1);" class="btn btn-danger">
              <i class="fa fa-times"></i>
              Cancel
            </a>
            <%= button_tag(type: 'submit', class: "btn btn-success pull-right") do %>
            <i class="fa fa-check"></i>
            Save
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer"></div>
  </div>
</div>
<% end %>

app/views/cards/_list_card.html.erb
<%= link_to(card, {:class => 'list-group-item'}) do %>
  <i class="fa fa-2x pull-left fa-user"></i>
<h4 class="list-group-item-heading"><%= card.display_title %> <%= display_active_star(card) %></h4>
  <p class="list-group-item-text"><%= card.category.display_name %></p>
<% end %>

app/views/cards/edit.html.erb
<% content_for :card_title, "Edit Card" %>
<%= render 'form' %>

app/views/cards/index.html.erb
<div class="col-sm-5 bootcards-list" id="list" data-title="Cards">
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left">Cards</h3>
      <div class="btn-group pull-right">
        <%= link_to new_card_path do %>
        <span>Add </span>
        <% end %>
      </div>
    </div>
    <div class="list-group">
      <% @cards.each do |card| %>
      <%= render partial: 'list_card', locals: {card: card} %>
      <% end %>
    </div>
    <div class="panel-footer"></div>
  </div>
</div>

app/views/cards/new.html.erb
<% content_for :card_title, "New Card" %>
<%= render 'form' %>

app/views/cards/show.html.erb
<div class="col-sm-5 bootcards-list" id="list" data-title="Cards">
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left"><%= @card.display_title %></h3>
      <div class="pull-right">
        <%= link_to 'Edit', edit_card_path(@card) %>
        -
        <%= form_for @card,  html: {:method => 'delete',:class => 'form-inline'} do |f| %>
        <%= link_to "Delete", "#", :onclick=>"edit_card_#{@card.id}.submit();" %>
        <% end %>
      </div>
    </div>
    <div class="list-group">
      <div class="list-group-item">
        <lable>Category</lable>
        <h3 class="list-group-item-heading"><%= @card.category.display_name %></h3>
      </div>
      <div class="list-group-item">
        <lable>Line 1</lable>
        <h3 class="list-group-item-heading"><%= @card.p_1 %></h3>
      </div>
      <div class="list-group-item">
        <lable>Line 2</lable>
        <h3 class="list-group-item-heading"><%= @card.p_2 %></h3>
      </div>
      <div class="list-group-item">
        <lable>Line 3</lable>
        <h3 class="list-group-item-heading"><%= @card.p_3 %></h3>
      </div>
      <div class="list-group-item">
        <lable>Line 4</lable>
        <h3 class="list-group-item-heading"><%= @card.p_4 %></h3>
      </div>
      <div class="list-group-item">
        <lable>Line 5</lable>
        <h3 class="list-group-item-heading"><%= @card.p_5 %></h3>
      </div>
    </div>
    <div class="panel-footer"></div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
<% if @category.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

  <ul>
    <% @category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="col-sm-5">
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left"><%= yield :card_title %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-3 form-group"><%f.label :name %> </div>
        <div class="col-sm-8 form-group"><%= f.text_field :name, {:class => 'form-control'} %></div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="btn-group pull-right">
            <a onclick="history.go(-1);" class="btn btn-danger">
              <i class="fa fa-times"></i>
              Cancel
            </a>
            <%= button_tag(type: 'submit', class: "btn btn-success pull-right") do %>
            <i class="fa fa-check"></i>
            Save
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer"></div>
  </div>
</div>
<% end %>

app/views/categories/_list_category.html.erb
<%= link_to(edit_category_path(category), {:class => 'list-group-item'}) do %>
  <i class="fa fa-2x pull-left fa-tag"></i>
  <h4 class="list-group-item-heading"><%= category.display_name %></h4>
  <p class="list-group-item-text"><%= category.updated_at %></p>
<% end %>

app/views/categories/edit.html.erb
<% content_for :card_title, "Edit Card" %>
<%= render 'form' %>

app/views/categories/index.html.erb
<div class="col-sm-5 bootcards-list" id="list" data-title="Card Categories">
  <div class="panel panel-default">
    <div class="panel-heading clearfix">
      <h3 class="panel-title pull-left">Card Categories</h3>
      <div class="btn-group pull-right">
        <%= link_to new_category_path do %>
        <span>Add </span>
        <% end %>
      </div>
    </div>
    <div class="list-group">
      <% @categories.each do |category| %>
      <%= render partial: 'list_category', locals: {category: category} %>
      <% end %>
    </div>
    <div class="panel-footer"></div>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :card_title, "New Card Category" %>
<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<div class="container-fluid">
  <% @cards.in_groups_of(3).each do |group| %>
  <div class="row">
    <% group.each do |item| %>
    <div class="item">
      <%= render_card(item) %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
<div class="row" id="message-row">  
  <div class="col-sm-12 alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
</div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <!-- fixed top navbar -->
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand no-break-out" title="GTPD - Duty Cards" href="/">GTPD - Duty Cards</a>  
      </div>
      <button type="button" class="btn btn-default btn-back pull-left hidden" onclick="history.back()">
        <i class="fa fa-lg fa-chevron-left"></i><span>Back</span>
      </button>
      <!-- menu button to show/ hide the off canvas slider -->
      <button type="button" class="btn btn-default btn-menu pull-left offCanvasToggle" data-toggle="offcanvas">
        <i class="fa fa-lg fa-bars"></i><span>Menu</span>
      </button>    
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="/" data-pjax="#main" data-title="Dashboard"
              <i class="fa fa-dashboard"></i>
              Dashboard
            </a>          
          </li>
          <li>
            <a href="/cards" data-pjax="#main" data-title="Cards"
              <i class="fa fa-user"></i>
              Cards
            </a>          
          </li>
          <li>
            <a href="/categories" data-pjax="#main" data-title="Card Categories"
              <i class="fa fa-tag"></i>
              Card Categories
            </a>          
          </li>
<!--
           <li>
            <a href="/contacts" data-pjax="#main" data-title="Contacts"
              <i class="fa fa-users"></i>
              Contacts
            </a>          
          </li>
-->
        </ul>
      </div>          
    </div>
  </div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gloucester Township Police - Duty Cards</title>
  <!-- CSS imports -->  
  <link rel="stylesheet"
        type="text/css"
        media="all"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.2/css/bootcards-desktop.min.css" />
  
  <link rel="stylesheet"
        media="all"
        href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
  
  <link rel="stylesheet"
        media="all"
        href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
        type="text/css" />
  
  <!-- Javascript imports -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.2/js/bootcards.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render partial: '/layouts/navigation' %>
    <%= render partial: '/layouts/messages' %>
    <%= yield %>
  </div>
</body>
</html>